# Site settings
title: LEAF &#x2014; Bering uClibc
email: your-email@domain.com
author:
  name: "LEAF Team"
  email: leaf-devel@lists.sourceforge.net
keywords: linux embedded appliance firewall network router vpn wireless
description: An easy to use embedded Linux network appliance for use in small office, home office, and home automation environments.
baseurl: ""
url: http://leaf.zetam.org
google_analytics_id: UA-52929925-1
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
exclude: [tools]

leaf_site_url: http://leaf.sourceforge.net
buc_wiki_url:  http://bering-uclibc.zetam.org/wiki
